//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace DiscogsDotNet.V2
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IDiscogsClientV2
    {

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Request Token
        /// </summary>
        /// <remarks>
        /// Generate the request token.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:authentication,header:authentication-request-token-url](https://www.discogs.com/developers/#page:authentication,header:authentication-request-token-url)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> Request_tokenAsync(string authorization = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Access Token
        /// </summary>
        /// <remarks>
        /// Generate the access token.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:authentication,header:authentication-access-token-url](https://www.discogs.com/developers/#page:authentication,header:authentication-access-token-url)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> Access_tokenAsync(string body = null, string authorization = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Releases
        /// </summary>
        /// <remarks>
        /// The Release resource represents a particular physical or digital object released by one or more Artists.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-release](https://www.discogs.com/developers/#page:database,header:database-release)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ReleasesGETAsync(string release_id, string content_Type = null, string user_Agent = null, string curr_abbr = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Release rating by user
        /// </summary>
        /// <remarks>
        /// Retrieves the release's rating for a given user.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-release-rating-by-user](https://www.discogs.com/developers/#page:database,header:database-release-rating-by-user)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> RatingGETAsync(string release_id, string username, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Release rating by user
        /// </summary>
        /// <remarks>
        /// Updates the release's rating for a given user. Authentication as the user is required. 
        /// <br/>
        /// <br/>The "rating" parameter must be sent inside a JSON object inside the request body.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-release-rating-by-user](https://www.discogs.com/developers/#page:database,header:database-release-rating-by-user)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> RatingPUTAsync(string release_id, string username, string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Release rating by user
        /// </summary>
        /// <remarks>
        /// Deletes the release's rating for a given user. Authentication as the user is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-release-rating-by-user](https://www.discogs.com/developers/#page:database,header:database-release-rating-by-user)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> RatingDELETEAsync(string release_id, string username, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Community release rating
        /// </summary>
        /// <remarks>
        /// The Community Release Rating endpoint retrieves the average rating and the total number of user ratings for a given release.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-community-release-rating](https://www.discogs.com/developers/#page:database,header:database-community-release-rating)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> RatingGET2Async(string release_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Master release
        /// </summary>
        /// <remarks>
        /// The Master resource represents a set of similar Releases. Masters (also known as “master releases”) have a “main release” which is often the chronologically earliest.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-master-release](https://www.discogs.com/developers/#page:database,header:database-master-release)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> MastersAsync(string master_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Master release versions
        /// </summary>
        /// <remarks>
        /// Retrieves a list of all Releases that are versions of this master. Accepts Pagination parameters.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-master-release-versions](https://www.discogs.com/developers/#page:database,header:database-master-release-versions)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> VersionsAsync(string master_id, string content_Type = null, string user_Agent = null, string page = null, string per_page = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Artist
        /// </summary>
        /// <remarks>
        /// Get an artist
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-artist](https://www.discogs.com/developers/#page:database,header:database-artist)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ArtistsAsync(string artist_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Artist releases
        /// </summary>
        /// <remarks>
        /// Returns a list of Releases and Masters associated with the Artist. Accepts Pagination.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-artist-releases](https://www.discogs.com/developers/#page:database,header:database-artist-releases)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ReleasesGET2Async(string content_Type = null, string user_Agent = null, string sort = null, string sort_order = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Label
        /// </summary>
        /// <remarks>
        /// Get a label
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-label](https://www.discogs.com/developers/#page:database,header:database-label)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> LabelsAsync(string label_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// All label releases
        /// </summary>
        /// <remarks>
        /// Returns a list of Releases associated with the label. Accepts Pagination parameters.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-all-label-releases](https://www.discogs.com/developers/#page:database,header:database-all-label-releases)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ReleasesGET3Async(string label_id, string content_Type = null, string user_Agent = null, string page = null, string per_page = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Search
        /// </summary>
        /// <remarks>
        /// Issue a search query to our database. This endpoint accepts pagination parameters. Authentication (as any user) is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:database,header:database-search](https://www.discogs.com/developers/#page:database,header:database-search)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> SearchAsync(string content_Type = null, string user_Agent = null, string query = null, string type = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Inventory
        /// </summary>
        /// <remarks>
        /// Returns the list of listings in a user's inventory. Accepts Pagination parameters.
        /// <br/>Basic information about each listing and the corresponding release is provided, suitable for display in a list. For detailed information about the release, make another API call to fetch the corresponding Release.
        /// <br/>
        /// <br/>If you are not authenticated as the inventory owner, only items that have a status of For Sale will be visible.
        /// <br/>If you are authenticated as the inventory owner you will get additional weight, format_quantity, external_id, and location keys.
        /// <br/>If the user is authorized, the listing will contain a in_cart boolean field indicating whether or not this listing is in their cart.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-inventory](https://www.discogs.com/developers/#page:marketplace,header:marketplace-inventory)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> InventoryAsync(string username, string content_Type = null, string user_Agent = null, string @string = null, string sort = null, string sort_order = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Listing
        /// </summary>
        /// <remarks>
        /// View the data associated with a listing.
        /// <br/>If the authorized user is the listing owner the listing will include the weight, format_quantity, external_id, and location keys. If the user is authorized, the listing will contain a in_cart boolean field indicating whether or not this listing is in their cart.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing](https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ListingsGETAsync(string listing_id, string content_Type = null, string user_Agent = null, string curr_abbr = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Listing
        /// </summary>
        /// <remarks>
        /// Edit the data associated with a listing.
        /// <br/>
        /// <br/>If the listing's status is not For Sale, Draft, or Expired, it cannot be modified – only deleted. To re-list a Sold listing, a new listing must be created.
        /// <br/>
        /// <br/>Authentication as the listing owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing](https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing)
        /// </remarks>
        /// <param name="release_id">The ID of the listing you are fetching</param>
        /// <param name="condition">The condition of the release you are posting. Must be one of the following: 
        /// <br/>• Mint (M)
        /// <br/>• Near Mint (NM or M-)
        /// <br/>• Very Good Plus (VG+)
        /// <br/>• Very Good (VG)
        /// <br/>• Good Plus (G+)
        /// <br/>• Good (G)
        /// <br/>• Fair (F)
        /// <br/>• Poor (P)</param>
        /// <param name="sleeve_condition">The condition of the sleeve of the item you are posting. Must be one of the following: 
        /// <br/>• Mint (M)
        /// <br/>• Near Mint (NM or M-)
        /// <br/>• Very Good Plus (VG+)
        /// <br/>• Very Good (VG)
        /// <br/>• Good Plus (G+)
        /// <br/>• Good (G)
        /// <br/>• Fair (F)
        /// <br/>• Poor (P)
        /// <br/>• Generic Not Graded No Cover</param>
        /// <param name="price">The price of the item (in the seller's currency).</param>
        /// <param name="comments">Any remarks about the item that will be displayed to buyers.</param>
        /// <param name="allow_offers">Whether or not to allow buyers to make offers on the item. Defaults to false.</param>
        /// <param name="status">The status of the listing. Defaults to For Sale. Options are For Sale (the listing is ready to be shown on the Marketplace) and Draft (the listing is not ready for public display).</param>
        /// <param name="external_id">A freeform field that can be used for the seller's own reference. Information stored here will not be displayed to anyone other than the seller. This field is called “Private Comments” on the Discogs website.</param>
        /// <param name="location">A freeform field that is intended to help identify an item's physical storage location. Information stored here will not be displayed to anyone other than the seller. This field will be visible on the inventory management page and will be available in inventory exports via the website.</param>
        /// <param name="weight">The weight, in grams, of this listing, for the purpose of calculating shipping. Set this field to auto to have the weight automatically estimated for you.</param>
        /// <param name="format_quantity">The number of items this listing counts as, for the purpose of calculating shipping. This field is called “Counts As” on the Discogs website. Set this field to auto to have the quantity automatically estimated for you.</param>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ListingsPOSTAsync(string listing_id, object body = null, string content_Type = null, string user_Agent = null, string release_id = null, string condition = null, string sleeve_condition = null, string price = null, string comments = null, string allow_offers = null, string status = null, string external_id = null, string location = null, string weight = null, string format_quantity = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Listing
        /// </summary>
        /// <remarks>
        /// Permanently remove a listing from the Marketplace. Authentication as the listing owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing](https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ListingsDELETEAsync(string listing_id, string content_Type = null, string user_Agent = null, string curr_abbr = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// New listing
        /// </summary>
        /// <remarks>
        /// Create a Marketplace listing. Authentication is required; the listing will be added to the authenticated user's Inventory.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-new-listing](https://www.discogs.com/developers/#page:marketplace,header:marketplace-new-listing)
        /// </remarks>
        /// <param name="release_id">The ID of the listing you are fetching</param>
        /// <param name="condition">The condition of the release you are posting. Must be one of the following: 
        /// <br/>• Mint (M)
        /// <br/>• Near Mint (NM or M-)
        /// <br/>• Very Good Plus (VG+)
        /// <br/>• Very Good (VG)
        /// <br/>• Good Plus (G+)
        /// <br/>• Good (G)
        /// <br/>• Fair (F)
        /// <br/>• Poor (P)</param>
        /// <param name="sleeve_condition">The condition of the sleeve of the item you are posting. Must be one of the following: 
        /// <br/>• Mint (M)
        /// <br/>• Near Mint (NM or M-)
        /// <br/>• Very Good Plus (VG+)
        /// <br/>• Very Good (VG)
        /// <br/>• Good Plus (G+)
        /// <br/>• Good (G)
        /// <br/>• Fair (F)
        /// <br/>• Poor (P)
        /// <br/>• Generic Not Graded No Cover</param>
        /// <param name="price">The price of the item (in the seller's currency).</param>
        /// <param name="comments">Any remarks about the item that will be displayed to buyers.</param>
        /// <param name="allow_offers">Whether or not to allow buyers to make offers on the item. Defaults to false.</param>
        /// <param name="status">The status of the listing. Defaults to For Sale. Options are For Sale (the listing is ready to be shown on the Marketplace) and Draft (the listing is not ready for public display).</param>
        /// <param name="external_id">A freeform field that can be used for the seller's own reference. Information stored here will not be displayed to anyone other than the seller. This field is called “Private Comments” on the Discogs website.</param>
        /// <param name="location">A freeform field that is intended to help identify an item's physical storage location. Information stored here will not be displayed to anyone other than the seller. This field will be visible on the inventory management page and will be available in inventory exports via the website.</param>
        /// <param name="weight">The weight, in grams, of this listing, for the purpose of calculating shipping. Set this field to auto to have the weight automatically estimated for you.</param>
        /// <param name="format_quantity">The number of items this listing counts as, for the purpose of calculating shipping. This field is called “Counts As” on the Discogs website. Set this field to auto to have the quantity automatically estimated for you.</param>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ListingsPOST2Async(object body = null, string content_Type = null, string user_Agent = null, string release_id = null, string condition = null, string sleeve_condition = null, string price = null, string comments = null, string allow_offers = null, string status = null, string external_id = null, string location = null, string weight = null, string format_quantity = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Order
        /// </summary>
        /// <remarks>
        /// View the data associated with a listing.
        /// <br/>If the authorized user is the listing owner the listing will include the weight, format_quantity, external_id, and location keys. If the user is authorized, the listing will contain a in_cart boolean field indicating whether or not this listing is in their cart.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing](https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> OrdersGETAsync(string order_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Order
        /// </summary>
        /// <remarks>
        /// dit the data associated with an order.
        /// <br/>Authentication as the seller is required.
        /// <br/>The response contains a next_status key – an array of valid next statuses for this order, which you can display to the user in (for example) a dropdown control. This also renders your application more resilient to any future changes in the order status logic.
        /// <br/>Changing the order status using this resource will always message the buyer with:
        /// <br/>
        /// <br/>Seller changed status from Old Status to New Status
        /// <br/>
        /// <br/>and does not provide a facility for including a custom message along with the change. For more fine-grained control, use the Add a new message resource, which allows you to simultaneously add a message and change the order status.
        /// <br/>If the order status is neither cancelled, Payment Received, nor Shipped, you can change the shipping. Doing so will send an invoice to the buyer and set the order status to Invoice Sent. (For that reason, you cannot set the shipping and the order status in the same request.)
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing](https://www.discogs.com/developers/#page:marketplace,header:marketplace-listing)
        /// </remarks>
        /// <param name="status">The status of the Order you are updating. Must be one of the following: 
        /// <br/>• New Order
        /// <br/>• Buyer Contacted
        /// <br/>• Invoice Sent
        /// <br/>• Payment Pending
        /// <br/>• Payment Received
        /// <br/>• Shipped
        /// <br/>• Refund Sent
        /// <br/>• Cancelled (Non-Paying Buyer)
        /// <br/>• Cancelled (Item Unavailable)
        /// <br/>• Cancelled (Per Buyer's Request)
        /// <br/>the order's current status
        /// <br/>
        /// <br/>Furthermore, the new status must be present in the order's next_status list. For more information about order statuses, see Edit an order.</param>
        /// <param name="shipping">The order shipping amount. As a side-effect of setting this value, the buyer is invoiced and the order status is set to Invoice Sent.</param>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> OrdersPOSTAsync(string order_id, object body = null, string content_Type = null, string user_Agent = null, string status = null, string shipping = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// List orders
        /// </summary>
        /// <remarks>
        /// Returns a list of the authenticated user's orders. Accepts Pagination parameters.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-list-orders](https://www.discogs.com/developers/#page:marketplace,header:marketplace-list-orders)
        /// </remarks>
        /// <param name="status">Only show orders with this status. Valid status keys are: 
        /// <br/>• All
        /// <br/>• New Order
        /// <br/>• Buyer Contacted
        /// <br/>• Invoice Sent
        /// <br/>• Payment Pending
        /// <br/>• Payment Received
        /// <br/>• Shipped
        /// <br/>• Merged
        /// <br/>• Order Changed
        /// <br/>• Refund Sent
        /// <br/>• Cancelled
        /// <br/>• Cancelled (Non-Paying Buyer)
        /// <br/>• Cancelled (Item Unavailable)
        /// <br/>• Cancelled (Per Buyer's Request) Cancelled (Refund Received)</param>
        /// <param name="sort">Sort items by this field (see below). Valid sort keys are: 
        /// <br/>• id
        /// <br/>• buyer
        /// <br/>• created
        /// <br/>• status
        /// <br/>• last_activity</param>
        /// <param name="sort_order">Sort items in a particular order (one of asc, desc)</param>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> OrdersGET2Async(string content_Type = null, string user_Agent = null, string status = null, string sort = null, string sort_order = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// List order messages
        /// </summary>
        /// <remarks>
        /// Returns a list of the order's messages with the most recent first. Accepts Pagination parameters.
        /// <br/>Authentication as the seller is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-list-order-messages](https://www.discogs.com/developers/#page:marketplace,header:marketplace-list-order-messages)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> MessagesGETAsync(string order_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// List order messages
        /// </summary>
        /// <remarks>
        /// Adds a new message to the order's message log.
        /// <br/>When posting a new message, you can simultaneously change the order status. If you do, the message will automatically be prepended with:
        /// <br/>
        /// <br/>Seller changed status from Old Status to New Status
        /// <br/>While message and status are each optional, one or both must be present.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-list-order-messages](https://www.discogs.com/developers/#page:marketplace,header:marketplace-list-order-messages)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> MessagesPOSTAsync(string order_id, object body = null, string content_Type = null, string user_Agent = null, string message = null, string status = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Fee
        /// </summary>
        /// <remarks>
        /// The Fee resource allows you to quickly calculate the fee for selling an item on the Marketplace.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-fee](https://www.discogs.com/developers/#page:marketplace,header:marketplace-fee
        /// <br/>)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> FeeAsync(string price, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Fee with currency
        /// </summary>
        /// <remarks>
        /// The Fee resource allows you to quickly calculate the fee for selling an item on the Marketplace given a particular currency.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-fee-with-currency](https://www.discogs.com/developers/#page:marketplace,header:marketplace-fee-with-currency)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> Fee2Async(string price, string currency, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Price suggestions
        /// </summary>
        /// <remarks>
        /// Retrieve price suggestions for the provided Release ID. If no suggestions are available, an empty object will be returned.
        /// <br/>Authentication is required, and the user needs to have filled out their seller settings. Suggested prices will be denominated in the user's selling currency.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:marketplace,header:marketplace-price-suggestions](https://www.discogs.com/developers/#page:marketplace,header:marketplace-price-suggestions)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> Price_suggestionsAsync(string release_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Export your inventory
        /// </summary>
        /// <remarks>
        /// Request an export of your inventory as a CSV.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:inventory-export,header:inventory-export-export-your-inventory](https://www.discogs.com/developers/#page:inventory-export,header:inventory-export-export-your-inventory)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ExportPOSTAsync(string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Recent exports
        /// </summary>
        /// <remarks>
        /// Get a list of all recent exports of your inventory. Accepts Pagination parameters.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:inventory-export,header:inventory-export-get-recent-exports](https://www.discogs.com/developers/#page:inventory-export,header:inventory-export-get-recent-exports)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ExportGETAsync(string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get an export
        /// </summary>
        /// <remarks>
        /// Get details about the status of an inventory export.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:inventory-export,header:inventory-export-get-an-export](https://www.discogs.com/developers/#page:inventory-export,header:inventory-export-get-an-export)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ExportGET2Async(string id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Download an export
        /// </summary>
        /// <remarks>
        /// Download the results of an inventory export.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:inventory-export,header:inventory-export-download-an-export](https://www.discogs.com/developers/#page:inventory-export,header:inventory-export-download-an-export)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> DownloadAsync(string id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Add inventory
        /// </summary>
        /// <remarks>
        /// Upload a CSV of listings to add to your inventory.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:inventory-upload,header:inventory-upload-add-inventory](https://www.discogs.com/developers/#page:inventory-upload,header:inventory-upload-add-inventory)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> AddAsync(string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Delete inventory
        /// </summary>
        /// <remarks>
        /// Upload a CSV of listings to delete from your inventory.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:inventory-upload,header:inventory-upload-delete-inventory](https://www.discogs.com/developers/#page:inventory-upload,header:inventory-upload-delete-inventory)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ChangeAsync(string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Recent uploads
        /// </summary>
        /// <remarks>
        /// Get a list of all recent inventory uploads. Accepts Pagination parameters.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:inventory-upload,header:inventory-upload-get-recent-uploads](https://www.discogs.com/developers/#page:inventory-upload,header:inventory-upload-get-recent-uploads)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> UploadAsync(string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Recent upload by ID
        /// </summary>
        /// <remarks>
        /// Get details about the status of an inventory upload.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:inventory-upload,header:inventory-upload-get-an-upload](https://www.discogs.com/developers/#page:inventory-upload,header:inventory-upload-get-an-upload)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> Upload2Async(string id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Identity
        /// </summary>
        /// <remarks>
        /// Retrieve basic information about the authenticated user.
        /// <br/>You can use this resource to find out who you're authenticated as, and it also doubles as a good sanity check to ensure that you're using OAuth correctly.
        /// <br/>For more detailed information, make another request for the user's Profile.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-identity,header:user-identity-identity](https://www.discogs.com/developers/#page:user-identity,header:user-identity-identity)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> IdentityAsync(string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Profile
        /// </summary>
        /// <remarks>
        /// Retrieve a user by username.
        /// <br/>
        /// <br/>If authenticated as the requested user, the email key will be visible, and the num_list count will include the user's private lists.
        /// <br/>
        /// <br/>If authenticated as the requested user or the user's collection/wantlist is public, the num_collection / num_wantlist keys will be visible.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-identity,header:user-identity-profile](https://www.discogs.com/developers/#page:user-identity,header:user-identity-profile)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> UsersGETAsync(string username, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Profile
        /// </summary>
        /// <remarks>
        /// Edit a user's profile data. Authentication as the user is required. Parameters must be filled in a json object inside the body. 
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-identity,header:user-identity-profile](https://www.discogs.com/developers/#page:user-identity,header:user-identity-profile)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> UsersPOSTAsync(string username, string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// User submissions
        /// </summary>
        /// <remarks>
        /// Retrieve a user's submissions by username. Accepts Pagination parameters.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-identity,header:user-identity-user-submissions](https://www.discogs.com/developers/#page:user-identity,header:user-identity-user-submissions)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> SubmissionsAsync(string username, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// User contributions
        /// </summary>
        /// <remarks>
        /// Retrieve a user's contributions by username. Accepts Pagination parameters. The Contributions resource represents releases, labels, and artists submitted by a user. 
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-identity,header:user-identity-user-contributions](https://www.discogs.com/developers/#page:user-identity,header:user-identity-user-contributions)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ContributionsAsync(string username, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Collection
        /// </summary>
        /// <remarks>
        /// Retrieve a list of folders in a user's collection. If the collection has been made private by its owner, authentication as the collection owner is required. If you are not authenticated as the collection owner, only folder ID 0 (the “All” folder) will be visible (if the requested user's collection is public).
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> FoldersGETAsync(string username, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Collection
        /// </summary>
        /// <remarks>
        /// Retrieve a list of folders in a user's collection. If the collection has been made private by its owner, authentication as the collection owner is required. If you are not authenticated as the collection owner, only folder ID 0 (the “All” folder) will be visible (if the requested user's collection is public).
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> FoldersPOSTAsync(string username, string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// List custom fields
        /// </summary>
        /// <remarks>
        /// Retrieve a list of user-defined collection notes fields. These fields are available on every release in the collection.
        /// <br/>
        /// <br/>If the collection has been made private by its owner, authentication as the collection owner is required.
        /// <br/>
        /// <br/>If you are not authenticated as the collection owner, only fields with public set to true will be visible.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-list-custom-fields](https://www.discogs.com/developers/#page:user-collection,header:user-collection-list-custom-fields)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> FoldersGET2Async(string username, string folder_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Collection folder
        /// </summary>
        /// <remarks>
        /// Edit a folder's metadata. Folders 0 and 1 cannot be renamed. Authentication as the collection owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-folder](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-folder)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> FoldersPOST2Async(string username, string folder_id, string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Collection folder
        /// </summary>
        /// <remarks>
        /// Delete a folder from a user's collection. A folder must be empty before it can be deleted. Authentication as the collection owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-folder](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-folder)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> FoldersDELETEAsync(string username, string folder_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Collection items by release
        /// </summary>
        /// <remarks>
        /// View the user's collection folders which contain a specified release. This will also show information about each release instance. The release_id must be non-zero.
        /// <br/>
        /// <br/>Authentication as the collection owner is required if the owner's collection is private.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-items-by-release](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-items-by-release)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ReleasesGET4Async(string username, string release_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Collection items by folder
        /// </summary>
        /// <remarks>
        /// Returns the list of item in a folder in a user's collection. Accepts Pagination parameters.
        /// <br/>
        /// <br/>Basic information about each release is provided, suitable for display in a list. For detailed information, make another API call to fetch the corresponding release.
        /// <br/>
        /// <br/>If folder_id is not 0, or the collection has been made private by its owner, authentication as the collection owner is required.
        /// <br/>
        /// <br/>If you are not authenticated as the collection owner, only public notes fields will be visible.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-items-by-folder](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-items-by-folder)
        /// </remarks>
        /// <param name="sort">Sort items by one of these fields: 
        /// <br/>• label
        /// <br/>• artist
        /// <br/>• title
        /// <br/>• catno
        /// <br/>• format
        /// <br/>• rating
        /// <br/>• added
        /// <br/>• year</param>
        /// <param name="sort_order">Sort items in a particular order (asc or desc)</param>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ReleasesGET5Async(string username, string folder_id, string content_Type = null, string user_Agent = null, string sort = null, string sort_order = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Add to collection folder
        /// </summary>
        /// <remarks>
        /// Add a release to a folder in a user's collection.
        /// <br/>
        /// <br/>The folder_id must be non-zero – you can use 1 for “Uncategorized”.
        /// <br/>
        /// <br/>Authentication as the collection owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-add-to-collection-folder](https://www.discogs.com/developers/#page:user-collection,header:user-collection-add-to-collection-folder)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ReleasesPOSTAsync(string username, string folder_id, string release_id, string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Change rating of release
        /// </summary>
        /// <remarks>
        /// Change the rating on a release and/or move the instance to another folder.
        /// <br/>
        /// <br/>This endpoint potentially takes 2 folder_id parameters: one in the URL (which is the folder you are requesting, and is required), and one in the request body (representing the folder you want to move the instance to, which is optional)
        /// <br/>
        /// <br/>Authentication as the collection owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-change-rating-of-release](https://www.discogs.com/developers/#page:user-collection,header:user-collection-change-rating-of-release)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> InstancesPOSTAsync(string username, string folder_id, string release_id, string instance_id, string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Delete instance from folder
        /// </summary>
        /// <remarks>
        /// Remove an instance of a release from a user's collection folder.
        /// <br/>
        /// <br/>To move the release to the “Uncategorized” folder instead, use the POST method.
        /// <br/>
        /// <br/>Authentication as the collection owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-delete-instance-from-folder](https://www.discogs.com/developers/#page:user-collection,header:user-collection-delete-instance-from-folder)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> InstancesDELETEAsync(string username, string folder_id, string release_id, string instance_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Edit fields instance
        /// </summary>
        /// <remarks>
        /// Change the value of a notes field on a particular instance.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-edit-fields-instance](https://www.discogs.com/developers/#page:user-collection,header:user-collection-edit-fields-instance)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> FieldsAsync(string username, string folder_id, string release_id, string instance_id, string field_id, string body = null, string content_Type = null, string user_Agent = null, string value = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Collection value
        /// </summary>
        /// <remarks>
        /// Returns the minimum, median, and maximum value of a user's collection.
        /// <br/>
        /// <br/>Authentication as the collection owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-value](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-value)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ValueAsync(string username, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Wantlist
        /// </summary>
        /// <remarks>
        /// Returns the list of releases in a user's wantlist. Accepts Pagination parameters.
        /// <br/>
        /// <br/>Basic information about each release is provided, suitable for display in a list. For detailed information, make another API call to fetch the corresponding release.
        /// <br/>
        /// <br/>If the wantlist has been made private by its owner, you must be authenticated as the owner to view it.
        /// <br/>
        /// <br/>The notes field will be visible if you are authenticated as the wantlist owner.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-wantlist,header:user-wantlist-wantlist](https://www.discogs.com/developers/#page:user-wantlist,header:user-wantlist-wantlist)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> WantsGETAsync(string username, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Add to wantlist
        /// </summary>
        /// <remarks>
        /// Add a release to a user's wantlist. Additional parameters must be send as JSON object inside the request body.
        /// <br/>
        /// <br/>Authentication as the wantlist owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-wantlist,header:user-wantlist-add-to-wantlist](https://www.discogs.com/developers/#page:user-wantlist,header:user-wantlist-add-to-wantlist)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> WantsPOSTAsync(string username, string release_id, string body = null, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Delete release from wantlist
        /// </summary>
        /// <remarks>
        /// Delete a release from a user's wantlist.
        /// <br/>
        /// <br/>Authentication as the wantlist owner is required.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-wantlist,header:user-wantlist-add-to-wantlist](https://www.discogs.com/developers/#page:user-wantlist,header:user-wantlist-add-to-wantlist)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> WantsDELETEAsync(string username, string release_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// User Lists
        /// </summary>
        /// <remarks>
        /// Returns a User's Lists. Private Lists will only display when authenticated as the owner. Accepts Pagination parameters.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-lists,header:user-lists-user-lists](https://www.discogs.com/developers/#page:user-lists,header:user-lists-user-lists)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> ListsAsync(string username, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// List
        /// </summary>
        /// <remarks>
        /// Returns items from a specified List. Private Lists will only display when authenticated as the owner.
        /// <br/>
        /// <br/>[https://www.discogs.com/developers/#page:user-lists,header:user-lists-list](https://www.discogs.com/developers/#page:user-lists,header:user-lists-list)
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="DiscogsClientV2Exception">A server side error occurred.</exception>
        System.Threading.Tasks.Task<object> Lists2Async(string list_id, string content_Type = null, string user_Agent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

    }

    



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DiscogsClientV2Exception : System.Exception
    {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public DiscogsClientV2Exception(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DiscogsClientV2Exception<TResult> : DiscogsClientV2Exception
    {
        public TResult Result { get; private set; }

        public DiscogsClientV2Exception(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625